<?php
/**
 * @file
 * Módulo que esconde os campos de placar quando um jogo é criado e apresenta os mesmos quando o node é editado.
 */

function change_forms_form_alter(&$form, $form_state, $form_id) {
//dpm($form);
//dsm($form['field_usr_sua_empresa']);
drupal_set_message("Form ID is : " . $form_id);
	if($form_id == 'user_profile_form'){
		global $user;
		$usr = user_load($user->uid);
		print '<pre>';
		//print_r($usr);
		print '</pre>';
		$items = field_get_items('user', $usr, 'field_usr_sua_empresa');
		print '<pre>';
		//print_r($items);
		print '</pre>';		
		print $items[0]['nid'];
		$empresa = $items[0]['nid'];
		$form['field_usr_sua_empresa']['#access'] = false;
		$form['account']['name']['#access'] = false;
		$form['account']['mail']['#access'] = false;
		$form['field_usr_cel']['#description'] = 'senha';

		$form['field_usr_sua_empresa']= array(
			'#type' => 'markup',
			'#prefix' => '<div class="empresa">',
			'#suffix' => '</div>'
		);
  		$form['field_usr_sua_empresa']['#markup'] = l('Clique aqui para editar sua empresa', 'node/'.$empresa.'/edit');
	}
	
}

function change_forms_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
 // dsm($form['field_usr_sua_empresa']); // essa funcao e fornecida pelo Devel

 // $form['field_usr_sua_empresa']['#type'] = 'markup';
 // $form['targeted_field']['#markup'] = l('Link', 'path/desejado');
}
 